### PR TITLE
Adding Api

### PR DESCRIPTION
**Pull request by SnakyMz**
Things I have done:

- [ ] Installed rails
- [ ] Added greeting model, controller, route
- [ ] Added link to frontend repository

[Link to the frontend repository](https://github.com/SnakyMz/hello-react-front-end)

### CODE REVIEW

**Review by Strangeal — CHANGES_REQUESTED** [review]
Hi @SnakyMz, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



## Highlights
- Good **PR** title ✅ 
- Descriptive *PR* description ✅ 
- Implement the features ✅ 
- Professional `README` template ✅ 
- Correct `GitHub` workflow ✅ 
- Meaningful **Github** commits ✅ 
- Correct `.github/workflows` for linters ✅ 
- Followed *best-practices* ✅ 
- Well structured project ✅ 

## Required Changes ♻️
- [ ] Great progress on your implementation! 👏 However, I've noticed an issue that's preventing the efficient loading of backend data for your frontend, leading to errors. 🚧 In the attached screenshot, you can see the details of the error I encountered while running your application.

   - Based on my experience, this could be related to `CORS` `(Cross-Origin Resource Sharing)` errors. To address this, consider integrating the `gem 'rack-cors'` into your project. It's a useful tool for handling CORS issues, ensuring smooth communication between your `frontend` and `backend`.

Screenshot 2023-11-28 at 21 32 06


 Let's work together to iron out these issues and enhance your project.


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by SnakyMz** [comment]
> Hi @SnakyMz,
> 
> Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there!
> 
> 
> 
> ## Highlights
> * Good **PR** title ✅
> * Descriptive _PR_ description ✅
> * Implement the features ✅
> * Professional `README` template ✅
> * Correct `GitHub` workflow ✅
> * Meaningful **Github** commits ✅
> * Correct `.github/workflows` for linters ✅
> * Followed _best-practices_ ✅
> * Well structured project ✅
> 
> ## Required Changes ♻️
> * [ ]  Great progress on your implementation! 👏 However, I've noticed an issue that's preventing the efficient loading of backend data for your frontend, leading to errors. 🚧 In the attached screenshot, you can see the details of the error I encountered while running your application.
>   
>   * Based on my experience, this could be related to `CORS` `(Cross-Origin Resource Sharing)` errors. To address this, consider integrating the `gem 'rack-cors'` into your project. It's a useful tool for handling CORS issues, ensuring smooth communication between your `frontend` and `backend`.
> 
> Screenshot 2023-11-28 at 21 32 06
> Let's work together to iron out these issues and enhance your project.
> 
> _Check the comments under the review._
> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

Thank you so much for the advise. I had very hard figuring it out. I will make changes as suggested. Thanks again

**Comment by SnakyMz** [comment]
# It's fixed now
@Strangeal Thank you again for the advise

Screenshot 2023-11-29 033143

**Review by joel-kalema — APPROVED** [review]
Hi @SnakyMz 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

# Congratulations! 🎉 


## Highlights

The project is running successfully 👍 
PR is well descriptive 👍 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@joel-kalema** in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
